<?php

namespace Database\Seeders;

use App\Models\MegaMenuItem;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MegaMenuItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $adminUser = User::where('role', 'admin')->first()
            ?? User::first()
            ?? User::factory()->create([
                'name' => 'Admin',
                'email' => 'admin@admin',
                'role' => 'admin',
            ]);

        $userId = $adminUser->id;

        $items = [
            // Compras
            [
                'title' => 'Amazon',
                'subtitle' => 'Compras online',
                'url' => 'https://www.amazon.com',
                'icon' => 'heroicon-o-shopping-cart',
                'color' => '#FF9900',
                'description' => 'Marketplace global com milhões de produtos.',
                'category' => 'Compras',
                'sort_order' => 1,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Mercado Livre',
                'subtitle' => 'Marketplace no Brasil',
                'url' => 'https://www.mercadolivre.com.br',
                'icon' => 'heroicon-o-shopping-cart',
                'color' => '#FBC02D',
                'description' => 'Marketplace líder com vendedores e lojas oficiais.',
                'category' => 'Compras',
                'sort_order' => 2,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'AliExpress',
                'subtitle' => 'Ofertas da Ásia',
                'url' => 'https://www.aliexpress.com',
                'icon' => 'heroicon-o-shopping-cart',
                'color' => '#FF4D4F',
                'description' => 'Produtos com preço baixo e variedade enorme.',
                'category' => 'Compras',
                'sort_order' => 3,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Shopee',
                'subtitle' => 'Ofertas e cupons',
                'url' => 'https://shopee.com.br',
                'icon' => 'heroicon-o-shopping-cart',
                'color' => '#EE4D2D',
                'description' => 'Marketplace com foco em promoções e frete grátis.',
                'category' => 'Compras',
                'sort_order' => 4,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'eBay',
                'subtitle' => 'Marketplace global',
                'url' => 'https://www.ebay.com',
                'icon' => 'heroicon-o-shopping-cart',
                'color' => '#0064D2',
                'description' => 'Leilões e vendas diretas no mundo todo.',
                'category' => 'Compras',
                'sort_order' => 5,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],

            // Redes Sociais
            [
                'title' => 'Facebook',
                'subtitle' => 'Rede social',
                'url' => 'https://www.facebook.com',
                'icon' => 'heroicon-o-user-group',
                'color' => '#1877F2',
                'description' => 'Conecte-se com amigos e comunidades.',
                'category' => 'Redes Sociais',
                'sort_order' => 6,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Instagram',
                'subtitle' => 'Fotos e vídeos',
                'url' => 'https://www.instagram.com',
                'icon' => 'heroicon-o-camera',
                'color' => '#E1306C',
                'description' => 'Compartilhe momentos em fotos e reels.',
                'category' => 'Redes Sociais',
                'sort_order' => 7,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'WhatsApp Web',
                'subtitle' => 'Mensagens no navegador',
                'url' => 'https://web.whatsapp.com',
                'icon' => 'heroicon-o-chat-bubble-left-right',
                'color' => '#25D366',
                'description' => 'Converse com seus contatos direto do navegador.',
                'category' => 'Redes Sociais',
                'sort_order' => 8,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'TikTok',
                'subtitle' => 'Vídeos curtos',
                'url' => 'https://www.tiktok.com',
                'icon' => 'heroicon-o-musical-note',
                'color' => '#000000',
                'description' => 'Crie e descubra vídeos curtos populares.',
                'category' => 'Redes Sociais',
                'sort_order' => 9,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'X (Twitter)',
                'subtitle' => 'Microblog',
                'url' => 'https://x.com',
                'icon' => 'heroicon-o-hashtag',
                'color' => '#000000',
                'description' => 'Siga notícias e tendências em tempo real.',
                'category' => 'Redes Sociais',
                'sort_order' => 10,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],

            // Notícias
            [
                'title' => 'G1',
                'subtitle' => 'Portal de notícias',
                'url' => 'https://g1.globo.com',
                'icon' => 'heroicon-o-newspaper',
                'color' => '#C53030',
                'description' => 'Notícias do Brasil e do mundo.',
                'category' => 'Notícias',
                'sort_order' => 11,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'UOL',
                'subtitle' => 'Notícias e entretenimento',
                'url' => 'https://www.uol.com.br',
                'icon' => 'heroicon-o-newspaper',
                'color' => '#F59E0B',
                'description' => 'Conteúdo variado com foco em notícias.',
                'category' => 'Notícias',
                'sort_order' => 12,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'BBC',
                'subtitle' => 'Notícias globais',
                'url' => 'https://www.bbc.com',
                'icon' => 'heroicon-o-newspaper',
                'color' => '#000000',
                'description' => 'Cobertura internacional de qualidade.',
                'category' => 'Notícias',
                'sort_order' => 13,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'CNN Brasil',
                'subtitle' => 'Cobertura nacional',
                'url' => 'https://www.cnnbrasil.com.br',
                'icon' => 'heroicon-o-newspaper',
                'color' => '#CC0000',
                'description' => 'Notícias e análise com foco no Brasil.',
                'category' => 'Notícias',
                'sort_order' => 14,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Reuters',
                'subtitle' => 'Agência de notícias',
                'url' => 'https://www.reuters.com',
                'icon' => 'heroicon-o-newspaper',
                'color' => '#374151',
                'description' => 'Atualizações econômicas e políticas globais.',
                'category' => 'Notícias',
                'sort_order' => 15,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],

            // Softwares Online
            [
                'title' => 'Google Drive',
                'subtitle' => 'Armazenamento em nuvem',
                'url' => 'https://drive.google.com',
                'icon' => 'heroicon-o-cloud',
                'color' => '#34A853',
                'description' => 'Arquivos e colaboração em nuvem.',
                'category' => 'Softwares Online',
                'sort_order' => 16,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Google Docs',
                'subtitle' => 'Produtividade online',
                'url' => 'https://docs.google.com',
                'icon' => 'heroicon-o-clipboard-document-check',
                'color' => '#F97316',
                'description' => 'Crie e edite documentos diretamente no navegador.',
                'category' => 'Softwares Online',
                'sort_order' => 17,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Notion',
                'subtitle' => 'Notas e wikis',
                'url' => 'https://www.notion.so',
                'icon' => 'heroicon-o-square-3-stack-3d',
                'color' => '#111827',
                'description' => 'Notas, documentos e bases de conhecimento.',
                'category' => 'Softwares Online',
                'sort_order' => 18,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Trello',
                'subtitle' => 'Kanban e projetos',
                'url' => 'https://trello.com',
                'icon' => 'heroicon-o-view-columns',
                'color' => '#0079BF',
                'description' => 'Organização de tarefas e projetos.',
                'category' => 'Softwares Online',
                'sort_order' => 19,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Figma',
                'subtitle' => 'Design colaborativo',
                'url' => 'https://www.figma.com',
                'icon' => 'heroicon-o-color-swatch',
                'color' => '#8B5CF6',
                'description' => 'Ferramenta de design e prototipação online.',
                'category' => 'Softwares Online',
                'sort_order' => 20,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],

            // Inteligência artificial
            [
                'title' => 'ChatGPT',
                'subtitle' => 'IA generativa',
                'url' => 'https://chatgpt.com',
                'icon' => 'heroicon-o-cube',
                'color' => '#10B981',
                'description' => 'Assistente conversacional com IA.',
                'category' => 'Inteligência Artificial',
                'sort_order' => 21,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Claude',
                'subtitle' => 'IA generativa',
                'url' => 'https://claude.ai',
                'icon' => 'heroicon-o-light-bulb',
                'color' => '#F59E0B',
                'description' => 'Assistente de IA focado em utilidade prática.',
                'category' => 'Inteligência Artificial',
                'sort_order' => 22,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Perplexity',
                'subtitle' => 'Pesquisa com IA',
                'url' => 'https://www.perplexity.ai',
                'icon' => 'heroicon-o-magnifying-glass-circle',
                'color' => '#3B82F6',
                'description' => 'Motor de busca orientado por IA.',
                'category' => 'Inteligência Artificial',
                'sort_order' => 23,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Gemini',
                'subtitle' => 'IA do Google',
                'url' => 'https://gemini.google.com',
                'icon' => 'heroicon-o-sparkles',
                'color' => '#7C3AED',
                'description' => 'Ferramenta de IA multimodal do Google.',
                'category' => 'Inteligência Artificial',
                'sort_order' => 24,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Copilot',
                'subtitle' => 'IA da Microsoft',
                'url' => 'https://copilot.microsoft.com',
                'icon' => 'heroicon-o-cpu-chip',
                'color' => '#2563EB',
                'description' => 'IA integrada ao ecossistema Microsoft.',
                'category' => 'Inteligência Artificial',
                'sort_order' => 25,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
        ];

        foreach ($items as $item) {
            $item['user_id'] = $userId;
            MegaMenuItem::create($item);
        }
    }
}
