<?php

namespace Database\Seeders;

use App\Models\MegaMenuItem;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MegaMenuItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public static function seedForUser(int $userId): void
    {
        foreach (self::defaultItems() as $item) {
            $item['user_id'] = $userId;
            MegaMenuItem::create($item);
        }
    }

    private static function defaultItems(): array
    {
        return [
            // Compras
            [
                'title' => 'Amazon',
                'subtitle' => 'Compras online',
                'url' => 'https://www.amazon.com',
                'icon' => 'heroicon-o-shopping-cart',
                'color' => '#FF9900',
                'description' => 'Marketplace global com milhões de produtos.',
                'category' => 'Compras',
                'sort_order' => 1,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Mercado Livre',
                'subtitle' => 'Marketplace no Brasil',
                'url' => 'https://www.mercadolivre.com.br',
                'icon' => 'heroicon-o-shopping-cart',
                'color' => '#FBC02D',
                'description' => 'Marketplace líder com vendedores e lojas oficiais.',
                'category' => 'Compras',
                'sort_order' => 2,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'AliExpress',
                'subtitle' => 'Ofertas da Ásia',
                'url' => 'https://www.aliexpress.com',
                'icon' => 'heroicon-o-shopping-cart',
                'color' => '#FF4D4F',
                'description' => 'Produtos com preço baixo e variedade enorme.',
                'category' => 'Compras',
                'sort_order' => 3,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Shopee',
                'subtitle' => 'Ofertas e cupons',
                'url' => 'https://shopee.com.br',
                'icon' => 'heroicon-o-shopping-cart',
                'color' => '#EE4D2D',
                'description' => 'Marketplace com foco em promoções e frete grátis.',
                'category' => 'Compras',
                'sort_order' => 4,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'eBay',
                'subtitle' => 'Marketplace global',
                'url' => 'https://www.ebay.com',
                'icon' => 'heroicon-o-shopping-cart',
                'color' => '#0064D2',
                'description' => 'Leilões e vendas diretas no mundo todo.',
                'category' => 'Compras',
                'sort_order' => 5,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],

            // Redes Sociais
            [
                'title' => 'Facebook',
                'subtitle' => 'Rede social',
                'url' => 'https://www.facebook.com',
                'icon' => 'heroicon-o-user-group',
                'color' => '#1877F2',
                'description' => 'Conecte-se com amigos e comunidades.',
                'category' => 'Redes Sociais',
                'sort_order' => 6,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Instagram',
                'subtitle' => 'Fotos e vídeos',
                'url' => 'https://www.instagram.com',
                'icon' => 'heroicon-o-camera',
                'color' => '#E1306C',
                'description' => 'Compartilhe momentos em fotos e reels.',
                'category' => 'Redes Sociais',
                'sort_order' => 7,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'WhatsApp Web',
                'subtitle' => 'Mensagens no navegador',
                'url' => 'https://web.whatsapp.com',
                'icon' => 'heroicon-o-chat-bubble-left-right',
                'color' => '#25D366',
                'description' => 'Converse com seus contatos direto do navegador.',
                'category' => 'Redes Sociais',
                'sort_order' => 8,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'TikTok',
                'subtitle' => 'Vídeos curtos',
                'url' => 'https://www.tiktok.com',
                'icon' => 'heroicon-o-musical-note',
                'color' => '#000000',
                'description' => 'Crie e descubra vídeos curtos populares.',
                'category' => 'Redes Sociais',
                'sort_order' => 9,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'X (Twitter)',
                'subtitle' => 'Microblog',
                'url' => 'https://x.com',
                'icon' => 'heroicon-o-hashtag',
                'color' => '#000000',
                'description' => 'Siga notícias e tendências em tempo real.',
                'category' => 'Redes Sociais',
                'sort_order' => 10,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],

            // Notícias
            [
                'title' => 'G1',
                'subtitle' => 'Portal de notícias',
                'url' => 'https://g1.globo.com',
                'icon' => 'heroicon-o-newspaper',
                'color' => '#C53030',
                'description' => 'Notícias do Brasil e do mundo.',
                'category' => 'Notícias',
                'sort_order' => 11,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'UOL',
                'subtitle' => 'Notícias e entretenimento',
                'url' => 'https://www.uol.com.br',
                'icon' => 'heroicon-o-newspaper',
                'color' => '#F59E0B',
                'description' => 'Conteúdo variado com foco em notícias.',
                'category' => 'Notícias',
                'sort_order' => 12,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'BBC',
                'subtitle' => 'Notícias globais',
                'url' => 'https://www.bbc.com',
                'icon' => 'heroicon-o-newspaper',
                'color' => '#000000',
                'description' => 'Cobertura internacional de qualidade.',
                'category' => 'Notícias',
                'sort_order' => 13,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'CNN Brasil',
                'subtitle' => 'Cobertura nacional',
                'url' => 'https://www.cnnbrasil.com.br',
                'icon' => 'heroicon-o-newspaper',
                'color' => '#CC0000',
                'description' => 'Notícias e análise com foco no Brasil.',
                'category' => 'Notícias',
                'sort_order' => 14,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Reuters',
                'subtitle' => 'Agência de notícias',
                'url' => 'https://www.reuters.com',
                'icon' => 'heroicon-o-newspaper',
                'color' => '#374151',
                'description' => 'Atualizações econômicas e políticas globais.',
                'category' => 'Notícias',
                'sort_order' => 15,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],

            // Softwares Online
            [
                'title' => 'Google Drive',
                'subtitle' => 'Armazenamento em nuvem',
                'url' => 'https://drive.google.com',
                'icon' => 'heroicon-o-cloud',
                'color' => '#34A853',
                'description' => 'Arquivos e colaboração em nuvem.',
                'category' => 'Softwares Online',
                'sort_order' => 16,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Google Docs',
                'subtitle' => 'Produtividade online',
                'url' => 'https://docs.google.com',
                'icon' => 'heroicon-o-clipboard-document-check',
                'color' => '#F97316',
                'description' => 'Crie e edite documentos diretamente no navegador.',
                'category' => 'Softwares Online',
                'sort_order' => 17,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Notion',
                'subtitle' => 'Notas e wikis',
                'url' => 'https://www.notion.so',
                'icon' => 'heroicon-o-square-3-stack-3d',
                'color' => '#111827',
                'description' => 'Notas, documentos e bases de conhecimento.',
                'category' => 'Softwares Online',
                'sort_order' => 18,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Trello',
                'subtitle' => 'Kanban e projetos',
                'url' => 'https://trello.com',
                'icon' => 'heroicon-o-view-columns',
                'color' => '#0079BF',
                'description' => 'Organização de tarefas e projetos.',
                'category' => 'Softwares Online',
                'sort_order' => 19,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Figma',
                'subtitle' => 'Design colaborativo',
                'url' => 'https://www.figma.com',
                'icon' => 'heroicon-o-color-swatch',
                'color' => '#8B5CF6',
                'description' => 'Ferramenta de design e prototipação online.',
                'category' => 'Softwares Online',
                'sort_order' => 20,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],

            // Inteligência artificial
            [
                'title' => 'ChatGPT',
                'subtitle' => 'IA generativa',
                'url' => 'https://chatgpt.com',
                'icon' => 'heroicon-o-cube',
                'color' => '#10B981',
                'description' => 'Assistente conversacional com IA.',
                'category' => 'Inteligência Artificial',
                'sort_order' => 21,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Claude',
                'subtitle' => 'IA generativa',
                'url' => 'https://claude.ai',
                'icon' => 'heroicon-o-light-bulb',
                'color' => '#F59E0B',
                'description' => 'Assistente de IA focado em utilidade prática.',
                'category' => 'Inteligência Artificial',
                'sort_order' => 22,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Perplexity',
                'subtitle' => 'Pesquisa com IA',
                'url' => 'https://www.perplexity.ai',
                'icon' => 'heroicon-o-magnifying-glass-circle',
                'color' => '#3B82F6',
                'description' => 'Motor de busca orientado por IA.',
                'category' => 'Inteligência Artificial',
                'sort_order' => 23,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Gemini',
                'subtitle' => 'IA do Google',
                'url' => 'https://gemini.google.com',
                'icon' => 'heroicon-o-sparkles',
                'color' => '#7C3AED',
                'description' => 'Ferramenta de IA multimodal do Google.',
                'category' => 'Inteligência Artificial',
                'sort_order' => 24,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Copilot',
                'subtitle' => 'IA da Microsoft',
                'url' => 'https://copilot.microsoft.com',
                'icon' => 'heroicon-o-cpu-chip',
                'color' => '#2563EB',
                'description' => 'IA integrada ao ecossistema Microsoft.',
                'category' => 'Inteligência Artificial',
                'sort_order' => 25,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            // Educação
            [
                'title' => 'Udemy',
                'subtitle' => 'Cursos online',
                'url' => 'https://www.udemy.com',
                'icon' => 'heroicon-o-academic-cap',
                'color' => '#A435F0',
                'description' => 'Cursos online com diversos temas.',
                'category' => 'Educação',
                'sort_order' => 26,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Alura',
                'subtitle' => 'Plataforma brasileira',
                'url' => 'https://www.alura.com.br',
                'icon' => 'heroicon-o-book-open',
                'color' => '#0066CC',
                'description' => 'Plataforma de cursos brasileira.',
                'category' => 'Educação',
                'sort_order' => 27,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Coursera',
                'subtitle' => 'Universidades online',
                'url' => 'https://www.coursera.org',
                'icon' => 'heroicon-o-academic-cap',
                'color' => '#0066CC',
                'description' => 'Cursos de universidades renomadas.',
                'category' => 'Educação',
                'sort_order' => 28,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Khan Academy',
                'subtitle' => 'Educação gratuita',
                'url' => 'https://www.khanacademy.org',
                'icon' => 'heroicon-o-academic-cap',
                'color' => '#14BF96',
                'description' => 'Educação gratuita para todos.',
                'category' => 'Educação',
                'sort_order' => 29,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Duolingo',
                'subtitle' => 'Aprenda idiomas',
                'url' => 'https://www.duolingo.com',
                'icon' => 'heroicon-o-globe-alt',
                'color' => '#58CC02',
                'description' => 'Aprenda idiomas de forma divertida.',
                'category' => 'Educação',
                'sort_order' => 30,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],

            // Finanças
            [
                'title' => 'Nubank',
                'subtitle' => 'Banco digital',
                'url' => 'https://www.nubank.com.br',
                'icon' => 'heroicon-o-credit-card',
                'color' => '#740DFF',
                'description' => 'Banco digital brasileiro.',
                'category' => 'Finanças',
                'sort_order' => 31,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Banco Inter',
                'subtitle' => 'Conta digital',
                'url' => 'https://www.bancointer.com.br',
                'icon' => 'heroicon-o-building-library',
                'color' => '#FF7A00',
                'description' => 'Banco digital com cashback.',
                'category' => 'Finanças',
                'sort_order' => 32,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Itaú',
                'subtitle' => 'Banco tradicional',
                'url' => 'https://www.itau.com.br',
                'icon' => 'heroicon-o-building-bank',
                'color' => '#ED1C24',
                'description' => 'Banco tradicional brasileiro.',
                'category' => 'Finanças',
                'sort_order' => 33,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'XP Investimentos',
                'subtitle' => 'Investimentos',
                'url' => 'https://www.xpi.com.br',
                'icon' => 'heroicon-o-chart-bar',
                'color' => '#1E40AF',
                'description' => 'Plataforma de investimentos.',
                'category' => 'Finanças',
                'sort_order' => 34,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Binance',
                'subtitle' => 'Exchange de cripto',
                'url' => 'https://www.binance.com',
                'icon' => 'heroicon-o-currency-dollar',
                'color' => '#F3BA2F',
                'description' => 'Exchange de criptomoedas.',
                'category' => 'Finanças',
                'sort_order' => 35,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],

            // Comunicação
            [
                'title' => 'WhatsApp',
                'subtitle' => 'Mensagens',
                'url' => 'https://web.whatsapp.com',
                'icon' => 'heroicon-o-chat-bubble-left-right',
                'color' => '#25D366',
                'description' => 'Mensagens instantâneas.',
                'category' => 'Comunicação',
                'sort_order' => 36,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Telegram',
                'subtitle' => 'Mensagens seguras',
                'url' => 'https://web.telegram.org',
                'icon' => 'heroicon-o-chat-bubble-left-right',
                'color' => '#0088CC',
                'description' => 'Mensagens seguras e rápidas.',
                'category' => 'Comunicação',
                'sort_order' => 37,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Slack',
                'subtitle' => 'Comunicação corporativa',
                'url' => 'https://app.slack.com',
                'icon' => 'heroicon-o-chat-bubble-left-right',
                'color' => '#36C5F0',
                'description' => 'Comunicação corporativa.',
                'category' => 'Comunicação',
                'sort_order' => 38,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Microsoft Teams',
                'subtitle' => 'Videoconferência',
                'url' => 'https://teams.microsoft.com',
                'icon' => 'heroicon-o-video-camera',
                'color' => '#0078D4',
                'description' => 'Colaboração e videoconferência.',
                'category' => 'Comunicação',
                'sort_order' => 39,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Discord',
                'subtitle' => 'Chat para comunidades',
                'url' => 'https://discord.com/app',
                'icon' => 'heroicon-o-chat-bubble-left-right',
                'color' => '#5865F2',
                'description' => 'Chat para comunidades.',
                'category' => 'Comunicação',
                'sort_order' => 40,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],
            [
                'title' => 'Portfólio',
                'subtitle' => 'Portfólio profissional',
                'url' => 'https://phelipecurty.vercel.app/',
                'icon' => 'heroicon-o-user',
                'color' => '#0F172A',
                'description' => 'Portfólio profissional com projetos e informações de Phelipe Curty.',
                'category' => 'YouTec',
                'sort_order' => 41,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],

            [
                'title' => 'YouTec Card',
                'subtitle' => 'Cartão digital',
                'url' => 'https://card.you.tec.br/',
                'icon' => 'heroicon-o-identification',
                'color' => '#8B5CF6',
                'description' => 'Cartão digital da plataforma YouTec para compartilhamento de informações.',
                'category' => 'YouTec',
                'sort_order' => 42,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],

            [
                'title' => 'Cardápio Virtual',
                'subtitle' => 'Menu digital',
                'url' => 'https://cardapiovirtual.space/',
                'icon' => 'heroicon-o-clipboard-document-list',
                'color' => '#22C55E',
                'description' => 'Plataforma de cardápio virtual para restaurantes e negócios.',
                'category' => 'YouTec',
                'sort_order' => 43,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],

            [
                'title' => 'Habilidade Tech',
                'subtitle' => 'Educação e tecnologia',
                'url' => 'https://habilidade.tech/',
                'icon' => 'heroicon-o-academic-cap',
                'color' => '#0EA5E9',
                'description' => 'Plataforma focada em desenvolvimento de habilidades tecnológicas.',
                'category' => 'YouTec',
                'sort_order' => 44,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],

            [
                'title' => 'Teste Tudo',
                'subtitle' => 'Ambiente de testes',
                'url' => 'https://testetudo.you.tec.br/',
                'icon' => 'heroicon-o-beaker',
                'color' => '#F59E0B',
                'description' => 'Ambiente da YouTec para testes e validações de funcionalidades.',
                'category' => 'YouTec',
                'sort_order' => 45,
                'is_active' => true,
                'open_in_new_tab' => true,
            ],

        ];
    }

    public function run(): void
    {
        $adminUser = User::where('role', 'admin')->first()
            ?? User::first()
            ?? User::factory()->create([
                'name' => 'Admin',
                'email' => 'admin@admin',
                'role' => 'admin',
            ]);

        $userId = $adminUser->id;

        self::seedForUser($userId);
    }
}
