services:

  laravel-php:
    image: php:8.4-fpm
    container_name: laravel-php
    restart: unless-stopped
    working_dir: /var/www

    volumes:
      - laravel-data:/var/www

    command: >
      bash -c "
      apt-get update &&
      apt install nodejs npm &&
      apt-get install -y git unzip curl libzip-dev zip libicu-dev &&
      curl -fsSL https://deb.nodesource.com/setup_20.x | bash - &&
      apt-get install -y nodejs &&
      
      docker-php-ext-install pdo pdo_mysql zip intl bcmath &&

      git config --global --add safe.directory /var/www &&

      if [ ! -f /var/www/artisan ]; then
        rm -rf /var/www/* &&
        git clone https://github.com/curtytech/start.space.git /var/www;
      fi &&

      cd /var/www &&

      if [ ! -f /usr/local/bin/composer ]; then
        curl -sS https://getcomposer.org/installer | php &&
        mv composer.phar /usr/local/bin/composer;
      fi &&

      composer install --no-interaction --prefer-dist --optimize-autoloader &&
      php artisan key:generate || true &&

      php-fpm -F 

      chown -R www-data:www-data .
      chmod -R 755 public
      chmod -R 775 storage bootstrap/cache
      "

    networks:
      - traefik-proxy


  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped

    volumes:
      - laravel-data:/var/www

    command: >
      sh -c "
      echo '
      server {
          listen 80;

          root /var/www/public;
          index index.php index.html;

          location / {
              try_files $$uri $$uri/ /index.php?$$query_string;
          }

          location ~ \.php$$ {
              fastcgi_pass laravel-php:9000;
              fastcgi_index index.php;
              include fastcgi_params;              
              fastcgi_param SCRIPT_FILENAME $$realpath_root$$fastcgi_script_name;
          }

          location ~ /\.ht {
              deny all;
          }
      }
      ' > /etc/nginx/conf.d/default.conf &&

      nginx -g 'daemon off;'
      "

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`vps.you.tec.br`)"
      - "traefik.http.routers.laravel.entrypoints=websecure"
      - "traefik.http.routers.laravel.tls.certresolver=letsencrypt"

    networks:
      - traefik-proxy

  ftp:
    image: fauria/vsftpd
    container_name: laravel-ftp
    restart: unless-stopped

    ports:
      - "21:21"
      - "21100-21110:21100-21110"

    environment:
      FTP_USER: laravel
      FTP_PASS: laravel123
      PASV_ADDRESS: 187.77.44.146
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110

    volumes:
      - laravel-data:/home/vsftpd/laravel

    networks:
      - traefik-proxy

volumes:
  laravel-data:

networks:
  traefik-proxy:
    external: true
